{
  "stages": [
    {
      "name": "ApplicationStop",
      "actions": [
        {
          "name": "StopContainer",
          "runas": "root",
          "commands": [
            "./scripts/stop_container.sh"
          ],
          "timeout": 300
        }
      ]
    },
    {
      "name": "AfterInstall",
      "actions": [
        {
          "name": "StartContainer",
          "runas": "root",
          "commands": [
            "./scripts/start_container.sh"
          ],
          "timeout": 300
        }
      ]
    }
  ]
}
